name: livegraphs-static
version: 0.1.0
private: true
description: A web dashboard for visualizing chatbot conversation analytics
homepage: https://notso.cloud/
bugs:
  url: https://github.com/kjanat/livegraphs-static/issues
repository:
  type: git
  url: git+https://github.com/kjanat/livegraphs-static.git
license: AGPL-3.0-or-later
author: Kaj Kowalski <dev@kajkowalski.nl>
scripts:
  build: next build
  build:static: cross-env DEPLOY_TARGET=static next build"
  build:edge: cross-env DEPLOY_TARGET=edge next build"
  build:node: cross-env DEPLOY_TARGET=node next build"
  dev: next dev
  dev:turbo: next dev --turbopack
  format: biome format --write
  format:check: biome format
  lint: |
    pnpm lint:next
    pnpm lint:biome
  lint:biome: biome check
  lint:next: next lint
  pre-commit: lint-staged
  prebuild: |
    mkdir -p public/sql-js
    cp node_modules/sql.js/dist/sql-wasm.* public/sql-js/
  prepare: husky
  start: |
    next build
    next start
  start:static: pnpm dlx serve out
  test: |
    NODE_OPTIONS='--max-old-space-size=8192 --expose-gc' \
    vitest run
  test:coverage: |
    NODE_OPTIONS='--max-old-space-size=8192 --expose-gc' \
    vitest run --coverage
  test:e2e: playwright test
  test:e2e:codegen: playwright codegen
  test:e2e:debug: playwright test --debug
  test:e2e:ui: playwright test --ui
  test:storybook: |
    NODE_OPTIONS='--max-old-space-size=8192 --expose-gc' \
    vitest run --config \
    vitest.storybook.config.ts
  test:ui: |
    NODE_OPTIONS='--max-old-space-size=8192 --expose-gc' \
    vitest --ui
  test:unit: |
    NODE_OPTIONS='--max-old-space-size=8192 --expose-gc' \
    vitest run
  test:watch: |
    NODE_OPTIONS='--max-old-space-size=8192 --expose-gc' \
    vitest
  type-check: tsc --noEmit
  validate: |
    pnpm format
    pnpm type-check
    pnpm lint
  storybook: storybook dev -p 6006
  build-storybook: storybook build
  preview: |
    opennextjs-cloudflare build
    opennextjs-cloudflare preview
  deploy: |
    opennextjs-cloudflare build
    opennextjs-cloudflare deploy
  upload: |
    opennextjs-cloudflare build
    opennextjs-cloudflare upload
  cf-typegen: |
    wrangler types \
      --env-interface CloudflareEnv \
      cloudflare-env.d.ts
lint-staged:
  'wrangler.{json,jsonc,toml}':
    - echo "🌀 Regenerating Cloudflare type declarations..." >&2
    - pnpm wrangler types --out-dir .
    - git add cloudflare-env.d.ts worker-configuration.d.ts
  '*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}':
    - biome check --write --no-errors-on-unmatched
#   package.json:
#     - pnpm dlx sort-package-json
dependencies:
  '@hookform/resolvers': ^5.2.0
  '@nivo/bar': ^0.99.0
  '@nivo/core': ^0.99.0
  '@nivo/heatmap': ^0.99.0
  '@nivo/pie': ^0.99.0
  '@opennextjs/cloudflare': ^1.6.1
  '@radix-ui/react-accordion': ^1.2.11
  '@radix-ui/react-alert-dialog': ^1.1.14
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-checkbox': ^1.3.2
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-hover-card': ^1.1.14
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.15
  '@radix-ui/react-navigation-menu': ^1.2.13
  '@radix-ui/react-popover': ^1.1.14
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.7
  '@radix-ui/react-scroll-area': ^1.2.9
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-switch': ^1.2.5
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-toggle': ^1.1.9
  '@radix-ui/react-toggle-group': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.7
  chart.js: ^4.5.0
  chartjs-adapter-date-fns: ^3.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  eventemitter3: ^5.0.1
  lucide-react: ^0.525.0
  next: ~15.3.5
  next-themes: ^0.4.6
  react: ^19.1.0
  react-chartjs-2: ^5.3.0
  react-day-picker: ^9.8.0
  react-dom: ^19.1.0
  react-gauge-component: ^1.2.64
  react-hook-form: ^7.61.1
  react-resizable-panels: ^3.0.3
  recharts: ~2.15.4
  sonner: ^2.0.6
  sql.js: ^1.13.0
  tailwind-merge: ^3.3.1
  vaul: ^1.1.2
  zod: ^4.0.10
devDependencies:
  '@biomejs/biome': 2.1.2
  '@chromatic-com/storybook': ^4.0.1
  '@eslint/eslintrc': ^3.3.1
  '@estruyf/github-actions-reporter': ^1.10.0
  '@next/eslint-plugin-next': ~15.3.5
  '@playwright/test': ^1.54.1
  '@size-limit/preset-app': ^11.2.0
  '@size-limit/webpack': ^11.2.0
  '@storybook/addon-a11y': ^9.0.18
  '@storybook/addon-docs': ^9.0.18
  '@storybook/addon-onboarding': ^9.0.18
  '@storybook/addon-vitest': ^9.0.18
  '@storybook/nextjs-vite': ^9.0.18
  '@tailwindcss/postcss': ^4.1.11
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^24.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/sql.js': ^1.4.9
  '@vitejs/plugin-react': ^4.7.0
  '@vitest/browser': 3.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  copy-webpack-plugin: ^13.0.0
  cross-env: ^10.0.0
  eslint: ^9.32.0
  eslint-config-next: ~15.3.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-storybook: ^9.0.18
  husky: ^9.1.7
  jsdom: ^26.1.0
  lint-staged: ^16.1.2
  playwright: ^1.54.1
  process: ^0.11.10
  size-limit: ^11.2.0
  storybook: ^9.0.18
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  vitest: ^3.2.4
  wrangler: ^4.26.0
packageManager: pnpm@10.13.1
